open-education-hub/actions

super-linter/config/config.json
Adding a newline inside a Markdown table is impossible without `<br>`. These kinds of elements are, however, forbidden my markdownlinter, as they represent a form of inline HTML.
Add rule inside general config to ignore this error.
Related-To: security-summer-school/essentials#42
=> super-linter: Allow `br` inside Markdown docs

spellcheck/config/spellcheck.yml
Add the `wordlists` item to the spellcheck configuration. Repositories can then store the `.wordlist.txt` file with custom words to be ignored by spellcheck.
=> spellcheck: Add wordlists to configuration

spellcheck/action.yml
Previously the spellcheck action linted the whole codebase. This made the output cluttered and unmanageable.
We overwrite the source files with the result of [another action](https://github.com/marketplace/actions/changed-files) which gets the changed files from a PR.
Mock PR: https://github.com/mariasfiraiala/essentials/actions/runs/5919293856/job/16049427316?pr=3
Mock action: https://github.com/mariasfiraiala/actions/tree/main/spellcheck
=> spellcheck: Check only the files amended in PR

super-linter/config/config.json
MD041 is a `markdownlint` rule that checks that all files start with a heading rule.
Disable it, as there may be cases where files don't start with a heading rule, or is not a 1st level (h1) heading rules.
=> `super-linter`: Disable MD041

super-linter/.textlintrc, super-linter/action.yml
Add `.textlintrc` configuration file for textlinter. It allows certain common words that `textlinter` (the terminology plugin) would complain about.
=> `super-linter`: Add configuration for `textlinter`

super-linter/CPPLINT.cfg, super-linter/action.yml
Add `CPPLINT.cfg` configuration file for `cpplint`. Also add workflow rule to download and use the configuration file.
=> `super-linter`: Add cpplint configuration

spellcheck/action.yml
If PRs are generated from forks, there might be situations when the main repository has more changes than the fork.
In this situation, the step that selects modified files will also select the files that are already upstream but are not present in the fork.
=> task: Fix spellcheck for PRs generated from forks

super-linter/rules/md104.js
Do not count the dot in float numbers as a punctuation mark.
=> super-linter: MD104 should ignore floats

super-linter/rules/md104.js
Do not count the dot in dates as a punctuation mark.
=> super-linter: MD104 should ignore dates

spellcheck/action.yml
'names.txt' was renamed to '.wordlist.txt' instead of '.names.txt'.
=> spellcheck: Fix names.txt path

spellcheck/config/spellcheck.yml
Ignore URLs and e-mail from spellchecking, as documented for pyspelling: https://facelessuser.github.io/pyspelling/filters/url/
=> spellcheck: Ignore URLs and e-mails

super-linter/config/config.json
Disable checking for raw urls whithing `.md` files.
=> super-linter/config: Disable rule MD034

super-linter/rules/md104.js
Add `vs.` as an exception to the line-splitting rule for Markdown linting (MD104), part of Super-Linter configuration.
=> super-linter: Ignore vs. for line-splitting

super-linter/rules/md104.js
If inside a LaTeX expression, ignore punctuation signs.
=> super-linter: Add exceptions for LaTeX inline in MD104

spellcheck/config/wordlist.txt
Also add the variations: "textboxes" and "multithreading".
=> spellcheck: Add "multithreaded" and "textbox"

spellcheck/config/technical.txt
Also add its derivatives: "casts", "casted", "casting".
=> spellcheck: Add "cast"

spellcheck/config/technical.txt
Add `iperf` and `speedtest` to the `technical.txt` wordlist.
=> spellcheck: Add `iperf` and `speedtest` to wordlist

spellcheck/config/acronyms.txt, spellcheck/config/technical.txt
Add words and acronyms such as `LLVM`, `wasmer` and `bytecode`.
=> spellcheck: Add words from OS exams

spellcheck/config/other_names.txt
Add application names from Unikraft catalog in the `other_names.txt` file.
=> spellcheck: Add Unikraft application names

spellcheck/config/technical.txt
This commit adds the "xxd" command as a valid word for the spell checker. This word is used as a correct answer in the memory security quiz.
=> spellcheck: Add word to wordlist

spellcheck/config/people_names.txt, spellcheck/config/technical.txt
Add words related to memry allocation in OS.
=> spellcheck: Add unknown words from OS memory assignment

checkpatch/action.yml
If available, check `.checkpatch.ignore` to see which directories to ignore.
This is a workaround since we are overwriting the `.checkpatch.conf` on repositories that run our action with our own.
See the example here: [`.checkpatch.ignore`](https://github.com/cs-pub-ro/operating-systems-internal/pull/45/files#diff-8e811e0db9b31e84ed3b72c3f35b8904282d28af03fdfab6afb5e3256dc4b777). This is used to ignore `inputs/` and `refs/` which have a lot of typos.
=> checkpatch: Use .checkpatch.ignore to ignore dirs

Makefile, README.md, typos/.typos.toml, typos/action.yml
Typos is an alternative to spellcheck. Unlike spellcheck, typos checks for common errors and does not require an extensive wordlist for technical terms and acronyms.
Add a Makefile rule to enable running the linter locally.
=> infra: Add typos linter

checkpatch/.checkpatch.ignore, checkpatch/action.yml
Ignore commented lines or sequences preceded by '#' inside `.checkpatch.ignore`.
Add an example for `.checkpatch.ignore.`
=> infra/typos: Allow comments in .checkpatch.ignore
