- spellcheck/action.yml
- spellcheck/config/spellcheck.yml
This is an attempt at adding a spell checker to the available actions. @gabrielmocanu You might find [the pattern for finding the md files](https://github.com/mariasfiraiala/actions/blob/9d7c7281d7eefe42fef5954127c6d8700d96e9bb/spellcheck/config/spellcheck.yml#L14) wrong. Apologies for that, I don't really have the means of testing this PR.
> spellcheck: Add spelling linter

- README.md
Use inline code formatting via backtick for action names in `REAMDE.md`.
> README.md: Use inline code formatting for action names

- checkpatch/action.yml
- cron-labeler/action.yml
- labeler/action.yml
- spellcheck/action.yml
- super-linter/action.yml
Update all links from SSS to OEH
> task: Update all links from SSS to OEH

- README.md
- Add SpellCheck description
- Add Cron-Labeler description
> task: Update README

- super-linter/action.yml
Update default branch for super-linter
> task: Update default branch for super-linter

- spellcheck/action.yml
Check only changed files with spellcheck
Fix: #15
> task: Check only changed files with spellcheck

- super-linter/action.yml
> task: Fix superlinter

- spellcheck/config/wordlist.txt
Expand wordlist to include words relevant to the Operating Systems class.
> spellcheck: Expand wordlist

- spellcheck/config/wordlist.txt
Add `localhost` and `repo` as new words.
> spellcheck: Add new words in wordlist

- spellcheck/config/wordlist.txt
This is needed for cs-pub-ro/operating-systems#43.
> spellcheck: Add "variadic" to the wordlist

- spellcheck/config/wordlist.txt
Add various terms used in mathematics and statistics. Add "archive networks": CTAN, CRAN, CPAN.
> spellcheck: Add words to wordlist

- spellcheck/config/wordlist.txt
Add "subdirectory" to wordlist.
> spellcheck: Add "subdirectory" to wordlist

- spellcheck/config/wordlist.txt
Add words related to cryptocurrency to spellcheck wordlist.
> spellcheck: Add cryptocurrency-related words to wordlist

- spellcheck/config/wordlist.txt
Add "facto" and "customizable" to wordlist.
> spellcheck: Update wordlist

- spellcheck/config/technical.txt
- spellcheck/config/wordlist.txt
Adds words used in quiz questions for Apache2 and Copy-On-Write sections.
> spellcheck: Add words to wordlists

- spellcheck/config/technical.txt
Add words used in quiz for the io chapter.
> spellcheck: Add words to wordlist related to OS

- spellcheck/config/technical.txt
Add words related to memory management in Operating Systems.
> spellcheck: Add OS memory-related words

- spellcheck/config/people_names.txt
I added the name because
https://github.com/cs-pub-ro/operating-systems/actions/runs/11372042882/job/31635466982?pr=99 fails
> speelcheck/config: Added name

- spellcheck/config/technical.txt
'unstage' is used in git related contexts.
> spellcheck/config: Add 'unstage'

- spellcheck/config/people_names.txt
- spellcheck/config/technical.txt
Add missing words related to OS Compute chapter.
> spellcheck: Complete words from OS Compute chapter

- spellcheck/config/acronyms.txt
- spellcheck/config/wordlist.txt
Add redirection(s) and config(s).
> spellcheck: Add words related to OS IO

- spellcheck/config/wordlist.txt
> spellcheck: Replace ’ with '

- spellcheck/config/other_names.txt
- spellcheck/config/wordlist.txt
Add words used in new Compute lecture quiz questions.
> spellcheck: Add unknown words from Compute lecture quiz

- spellcheck/config/technical.txt
- spellcheck/config/wordlist.txt
For PR: https://github.com/cs-pub-ro/operating-systems/pull/137
> spellcheck: Add terms for Aplication-Interaction chapter
